import os
import re
from datetime import datetime
from typing import Dict, Any

from fpdf import FPDF


class _StrategyPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(26, 82, 118)
        self.cell(0, 12, "AI-Powered Product Strategy Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(127, 140, 141)
        self.cell(
            0, 7,
            f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')} | Confidential",
            align="C", new_x="LMARGIN", new_y="NEXT",
        )
        self.ln(2)
        self.set_draw_color(41, 128, 185)
        self.set_line_width(0.8)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(149, 165, 166)
        self.cell(0, 8, f"Page {self.page_no()} | AI Product Strategy Assistant", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(255, 255, 255)
        self.set_fill_color(41, 128, 185)
        self.cell(0, 9, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(44, 62, 80)
        self.multi_cell(0, 5, text)
        self.ln(4)


def _strip_markdown(text: str) -> str:
    text = re.sub(r"#{1,6}\s+", "", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"\*([^*]+)\*", r"\1", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    # Replace bullet-like characters that may cause encoding issues
    text = text.replace("•", "-").replace("–", "-").replace("—", "--")
    text = text.replace("‘", "'").replace("’", "'").replace("“", '"').replace("”", '"')
    return text.strip()


def _safe(text: str) -> str:
    """Encode to latin-1, replacing unsupported characters."""
    return text.encode("latin-1", errors="replace").decode("latin-1")


SECTIONS = [
    ("Executive Summary", "executive_summary"),
    ("Customer Insights Report", "customer_insights"),
    ("Market Research Summary", "market_research"),
    ("Competitor Analysis Report", "competitor_analysis"),
    ("SWOT Analysis", "swot_analysis"),
    ("Product Opportunity Assessment", "opportunity_assessment"),
    ("Feature Prioritization Recommendations", "feature_priorities"),
    ("Product Roadmap Suggestions", "product_roadmap"),
    ("Strategic Recommendations & Action Plan", "strategy_recommendations"),
]


def generate_pdf(report_data: Dict[str, Any], output_path: str) -> str:
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    pdf = _StrategyPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Cover intro
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(52, 73, 94)
    pdf.multi_cell(
        0, 6,
        "This report was automatically generated by the AI Product Strategy Assistant. "
        "It synthesizes insights from uploaded business data through a multi-agent AI pipeline "
        "covering customer feedback analysis, market research, competitor benchmarking, "
        "SWOT analysis, feature prioritization, and strategic planning.",
    )
    pdf.ln(6)

    for title, key in SECTIONS:
        content = report_data.get(key, "")
        if not content:
            continue
        pdf.section_title(title)
        pdf.body_text(_safe(_strip_markdown(content)))
        if pdf.get_y() > 255:
            pdf.add_page()

    pdf.output(output_path)
    return output_path
